name: action-build-docs
description: "builds the documentation folder and commits it to the github pages branch"

runs:
  using: composite
  steps:
    - name: deno-task test
      shell: bash
      run: deno task test

    - name: deno-task build-docs
      shell: bash
      run: deno task build-docs "/layout_engi_ts/"

    - name: add clear-list-file in order to ignore deletion of the /examples/assets/ folder
      shell: bash
      run: |
        echo "**/*" >> ./.clear-target-files.txt
        echo "!.git" >> ./.clear-target-files.txt
        echo "!examples/assets/grid_images/*" >> ./.clear-target-files.txt

    - name: create gh-pages branch
      uses: s0/git-publish-subdir-action@develop
      env:
        REPO: self
        BRANCH: gh-pages
        FOLDER: docs
        CLEAR_GLOBS_FILE: ".clear-target-files"
        GITHUB_TOKEN: ${{ inputs.GITHUB_TOKEN }}
