export { Array2DShape, rotateArray2DMajor, rotateArray2DMinor, spliceArray2DMajor, spliceArray2DMinor, transposeArray2D } from "https://deno.land/x/kitchensink_ts@v0.7.0/array2d.ts"
export type { Array2D, Array2DColMajor, Array2DRowMajor } from "https://deno.land/x/kitchensink_ts@v0.7.0/array2d.ts"
export { cumulativeSum } from "https://deno.land/x/kitchensink_ts@v0.7.0/numericarray.ts"
export { max, min, sum } from "https://deno.land/x/kitchensink_ts@v0.7.0/numericmethods.ts"
export { constructFrom, constructorOf } from "https://deno.land/x/kitchensink_ts@v0.7.0/struct.ts"
export type { ConstructorOf, MethodsOf } from "https://deno.land/x/kitchensink_ts@v0.7.0/typedefs.ts"
//export * from "https://deno.land/x/kitchensink_ts@v0.7.0/builtin_aliases.ts"

//export * from "https://esm.sh/solid-js?d.ts"
//export type * from "https://esm.sh/solid-js?d.ts"
//export * from "file:///D:/My works/2022/deno_rewrites/kitchensink_ts/src/signal.ts"
export { Context, MemoSignal_Factory, StateSignal_Factory } from "https://deno.land/x/tsignal_ts@v0.1.1/mod.ts"
export type { Accessor, Setter } from "https://deno.land/x/tsignal_ts@v0.1.1/mod.ts"
